name = "stdlib_sorting"
version = "0.1.0"
license = "MIT"
author = "Tomohiro Degawa"
maintainer = "@degawa/stdlib_modules"
copyright = "2021 Tomohiro Degawa"

[dependencies]
stdlib_version = {git = "https://github.com/degawa/stdlib_modules", branch="stdlib_version-fpm"}
stdlib_kinds = {git = "https://github.com/degawa/stdlib_modules", branch="stdlib_kinds-fpm"}
stdlib_optval = {git = "https://github.com/degawa/stdlib_modules", branch="stdlib_optval-fpm"}
stdlib_string_type = {git = "https://github.com/degawa/stdlib_modules", branch="stdlib_string_type-fpm"}
