name = "stdlib_array"
version = "0.1.0"
license = "MIT"
author = "Tomohiro Degawa"
maintainer = "@degawa/stdlib_modules"
copyright = "2021 Tomohiro Degawa"

[dependencies]
stdlib_version = {git = "https://github.com/degawa/stdlib_modules", branch="stdlib_version-fpm"}
