name = "stdlib_hash"
version = "0.2.1"
license = "MIT"
author = "Tomohiro Degawa"
maintainer = "@degawa/stdlib_modules"
copyright = "2021-2022 Tomohiro Degawa"

[dependencies]
stdlib_version = {git = "https://github.com/degawa/stdlib_modules", branch="stdlib_version-fpm"}
stdlib_kinds = {git = "https://github.com/degawa/stdlib_modules", branch="stdlib_kinds-fpm"}
